# Deploy script

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - production

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: site/package-lock.json
          node-version: 16.13.x
          cache: npm

      - name: Open site folder
        run: cd site

      - name: Install packages
        run: npm ci

      - name: Run deploy script
        run: npm run deploy
