# Deploy script

name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - production

defaults:
  run:
    working-directory: site

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: site/package-lock.json
          node-version: 16.13.x
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
